version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "bowl_spb"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    restart: always
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code/
      - /var/www/bowl_fbspb/media/:/code/media/
    ports:
      - "8080:8080"
    depends_on:
      - postgres