# Generated by Django 4.2 on 2023-04-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secondpmmodel",
            name="game_10",
            field=models.SmallIntegerField(null=True, verbose_name="Игра 10"),
        ),
        migrations.AlterField(
            model_name="secondpmmodel",
            name="game_11",
            field=models.SmallIntegerField(null=True, verbose_name="Игра 11"),
        ),
        migrations.AlterField(
            model_name="secondpmmodel",
            name="game_12",
            field=models.SmallIntegerField(null=True, verbose_name="Игра 12"),
        ),
        migrations.AlterField(
            model_name="secondpmmodel",
            name="game_13",
            field=models.SmallIntegerField(null=True, verbose_name="Игра 13"),
        ),
        migrations.AlterField(
            model_name="secondpmmodel",
            name="game_14",
            field=models.SmallIntegerField(null=True, verbose_name="Игра 14"),
        ),
        migrations.AlterField(
            model_name="secondpmmodel",
            name="game_15",
            field=models.SmallIntegerField(null=True, verbose_name="Игра 15"),
        ),
        migrations.AlterField(
            model_name="secondpmmodel",
            name="game_16",
            field=models.SmallIntegerField(null=True, verbose_name="Игра 16"),
        ),
        migrations.AlterField(
            model_name="secondpmmodel",
            name="game_17",
            field=models.SmallIntegerField(null=True, verbose_name="Игра 17"),
        ),
        migrations.AlterField(
            model_name="secondpmmodel",
            name="game_7",
            field=models.SmallIntegerField(null=True, verbose_name="Игра 7"),
        ),
        migrations.AlterField(
            model_name="secondpmmodel",
            name="game_8",
            field=models.SmallIntegerField(null=True, verbose_name="Игра 8"),
        ),
        migrations.AlterField(
            model_name="secondpmmodel",
            name="game_9",
            field=models.SmallIntegerField(null=True, verbose_name="Игра 9"),
        ),
    ]
