# Generated by Django 4.2 on 2023-04-25 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_secondpmmodel_game_10_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sum", models.IntegerField(verbose_name="Сумма")),
                (
                    "avg",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Средний"
                    ),
                ),
                ("place", models.SmallIntegerField(verbose_name="Место")),
                ("game_1", models.SmallIntegerField(verbose_name="Игра 1")),
                ("game_2", models.SmallIntegerField(verbose_name="Игра 2")),
                ("game_3", models.SmallIntegerField(verbose_name="Игра 3")),
                ("game_4", models.SmallIntegerField(verbose_name="Игра 4")),
                ("game_5", models.SmallIntegerField(verbose_name="Игра 5")),
                ("game_6", models.SmallIntegerField(verbose_name="Игра 6")),
                ("game_7", models.SmallIntegerField(null=True, verbose_name="Игра 7")),
                ("game_8", models.SmallIntegerField(null=True, verbose_name="Игра 8")),
                ("game_9", models.SmallIntegerField(null=True, verbose_name="Игра 9")),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.playermodel",
                        verbose_name="Игрок",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.resultsmodel",
                        verbose_name="Турнир",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.yearmodel",
                        verbose_name="Год",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
