# Generated by Django 3.1.7 on 2023-04-27 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230427_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesmodel',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='imagesmodel',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='documentmodel',
            name='type',
            field=models.CharField(choices=[('regulation', 'Регламент'), ('rang_report', 'Приказ о присвоении')], max_length=100, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='imagesmodel',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news_imgs', to='main.newsmodel', verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='newsdocuments',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news_documents', to='main.newsmodel', verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Просмотров'),
        ),
    ]
