# Generated by Django 3.1.7 on 2023-04-27 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230427_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesmodel',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news_images', to='main.newsmodel', verbose_name='Новость'),
        ),
    ]
