# Generated by Django 3.1.7 on 2023-04-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230427_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultsmodel',
            name='type',
            field=models.CharField(choices=[('FirstPm', '1 регламент ПМ'), ('SecondPm', '2 регламент ПМ'), ('Teams', 'Пары'), ('Teams', 'Пары микс'), ('Teams', 'Тройки')], max_length=100, verbose_name='Тип турнира'),
        ),
    ]
