# Generated by Django 3.1.7 on 2023-04-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20230427_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsmodel',
            name='format',
            field=models.CharField(choices=[('rating', 'Рейтинговый'), ('sport', 'Спортивный')], default='rating', max_length=50, verbose_name='Формат'),
            preserve_default=False,
        ),
    ]
