# Generated by Django 3.1.7 on 2023-05-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_resultsmodel_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarmodel',
            name='status',
            field=models.CharField(default='dsasd', max_length=100, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
