# Generated by Django 3.1.7 on 2023-05-06 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_calendarmodel_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarmodel',
            options={'ordering': ['date_start'], 'verbose_name': 'турнир', 'verbose_name_plural': 'Календарь турниров'},
        ),
        migrations.RenameField(
            model_name='calendarmodel',
            old_name='end_date',
            new_name='date_finish',
        ),
        migrations.RenameField(
            model_name='calendarmodel',
            old_name='start_date',
            new_name='date_start',
        ),
        migrations.RemoveField(
            model_name='calendarmodel',
            name='tournament',
        ),
        migrations.AddField(
            model_name='calendarmodel',
            name='competition',
            field=models.CharField(default='asd', max_length=50, verbose_name='Название турнира'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendarmodel',
            name='type',
            field=models.CharField(choices=[('Sport', 'Спортивный'), ('Student', 'Студенческий')], default='Sport', max_length=20, verbose_name='Тип турнира'),
        ),
        migrations.AlterField(
            model_name='calendarmodel',
            name='city',
            field=models.CharField(max_length=20, verbose_name='Город проведения'),
        ),
        migrations.AlterField(
            model_name='calendarmodel',
            name='regulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.documentmodel', verbose_name='Регламент'),
        ),
        migrations.AlterField(
            model_name='calendarmodel',
            name='status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Статус соревнований'),
        ),
    ]
